### ISSUE TITLE
Can not make library to work on android studio

### ISSUE THREAD

**Issue by panagorn** [LivotovLabs/zxscanlib#15]
Hello i added your library using Gradle but it can not find version 1.0.0 i change it to 2.0.0-SNAPSHOT and when is build it shows me this Error:Execution failed for task ':app:processDebugManifest'.
> Multiple entries with same key: android:label=REPLACE and @android:label=REPLACE. What i have to do to make this work? Thank you in advance

Now i get this error

Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/Users/..../Desktop/adt-bundle-mac-x86_64-20140702/sdk/build-tools/21.1.2/dx --dex --no-optimize --output /Users/panayiotis/Documents/..../app/build/intermediates/dex/debug --input-list=/Users/.../Documents/..../app/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
  	2
  Output:
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Lcom/google/zxing/BarcodeFormat;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)

**Comment by livotov** [comment]
Hi !

Right, only v 2.0.0-SNAPSHOT is gradle-enabled. You're attaching it as a dependency to your project, (using compile statement in gradle file) right  ?

Let me try it with the Studio 1.0.0 later tonight (never tried yet as mainly sit on IDEA 14) - maybe a bug in my configuration.  Will let you know.

**Comment by panagorn** [comment]
ok thank u
