### ISSUE TITLE
 Failed to open a camera

### ISSUE THREAD

**Issue by Dimezis** [LivotovLabs/zxscanlib#19]
Android 5.0.2 (CM), Sony Xperia V.
java.lang.RuntimeException: Failed to open a camera with id 0: Fail to connect to camera service

when doing scanner.startScanner();

**Comment by livotov** [comment]
Maybe a camera permission problem ? 
Does the demo app work (one, included with this library) or fails either ?

**Comment by jazzyarchitects** [comment]
**I am also facing the same problem with scanner.startScanner();
Using Galaxy Grand Neo, Android 4.2.2
Here is the log:**


java.lang.RuntimeException: Failed to open a camera with id 0: Fail to connect to camera service
            at eu.livotov.labs.android.camview.CAMView.setupCamera(CAMView.java:536)
            at eu.livotov.labs.android.camview.CAMView.start(CAMView.java:178)
            at eu.livotov.labs.android.camview.CAMView.start(CAMView.java:172)
            at eu.livotov.zxscan.ScannerView.startScanner(ScannerView.java:75)
            at com.scribblernotebooks.scribblernotebooks.Activities.ScannerActivity.startScan(ScannerActivity.java:102)
            at com.scribblernotebooks.scribblernotebooks.Activities.ScannerActivity$1$1.onTextChanged(ScannerActivity.java:56)
            at android.widget.TextView.sendOnTextChanged(TextView.java:8273)
            at android.widget.TextView.handleTextChanged(TextView.java:8337)
            at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:10344)
            at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:962)
            at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:496)
            at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:435)
            at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:30)
            at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:676)
            at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:196)
            at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:183)
            at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:279)
            at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:77)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:176)
            at android.app.ActivityThread.main(ActivityThread.java:5302)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: Fail to connect to camera service
            at android.hardware.Camera.native_setup(Native Method)
            at android.hardware.Camera.<init>(Camera.java:410)
            at android.hardware.Camera.open(Camera.java:365)
            at eu.livotov.labs.android.camview.CAMView.openCamera(CAMView.java:543)
            at eu.livotov.labs.android.camview.CAMView.setupCamera(CAMView.java:531)
            at eu.livotov.labs.android.camview.CAMView.start(CAMView.java:178)
            at eu.livotov.labs.android.camview.CAMView.start(CAMView.java:172)
            at eu.livotov.zxscan.ScannerView.startScanner(ScannerView.java:75)
            at com.scribblernotebooks.scribblernotebooks.Activities.ScannerActivity.startScan(ScannerActivity.java:102)
            at com.scribblernotebooks.scribblernotebooks.Activities.ScannerActivity$1$1.onTextChanged(ScannerActivity.java:56)
            at android.widget.TextView.sendOnTextChanged(TextView.java:8273)
            at android.widget.TextView.handleTextChanged(TextView.java:8337)
            at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:10344)
            at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:962)
            at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:496)
            at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:435)
            at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:30)
            at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:676)
            at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:196)
            at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:183)
            at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:279)
            at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:77)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:176)
            at android.app.ActivityThread.main(ActivityThread.java:5302)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by livotov** [comment]
check the camera access permission records in your manifest please
